import type { Metadata } from "next";
import { FaHeart } from "react-icons/fa";
import { IoMdCalendar } from "react-icons/io";
import { IoHomeOutline, IoPizzaOutline } from "react-icons/io5";
import { PiShoppingBagOpen } from "react-icons/pi";
export const metadata: Metadata = {
	title: "Home",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<section className=" flex flex-row ">
			<div className=" w-18 rounded-r-lg h-auto bg-red-400 ">
				<div className="h-1/5 hover:bg-slate-400  m-1 hover:rounded-lg flex ">
					<div className="relative h-1/2 w-full flex place-content-center  my-auto ">
						<IoHomeOutline className="text-5xl text-white hover:drop-shadow-xl " />
					</div>
				</div>
				<div className="h-1/5 hover:bg-slate-400  m-1 hover:rounded-lg flex ">
					<div className="relative h-1/2 w-full flex place-content-center  my-auto ">
						<IoPizzaOutline className="text-6xl text-white hover:drop-shadow-xl " />
					</div>
				</div>
				<div className="h-1/5 hover:bg-slate-400  m-1 hover:rounded-lg flex ">
					<div className="relative h-1/2 w-full flex place-content-center  my-auto ">
						<IoMdCalendar className="text-5xl text-white hover:drop-shadow-xl " />
					</div>
				</div>
				<div className="h-1/5 hover:bg-slate-400  m-1 hover:rounded-lg flex ">
					<div className="relative h-1/2 w-full flex place-content-center  my-auto ">
						<PiShoppingBagOpen className="text-5xl text-white hover:drop-shadow-xl " />
					</div>
				</div>
				<div className="h-1/5 hover:bg-slate-400  m-1 hover:rounded-lg flex ">
					<div className="relative h-1/2 w-full flex place-content-center  my-auto ">
						<FaHeart className="text-5xl text-white hover:drop-shadow-xl " />
					</div>
				</div>
			</div>
			<div>{children}</div>
		</section>
	);
}
